### ISSUE TITLE
createVoiceEnrollment error

### ISSUE THREAD

**Issue by dineshmaths1** [voiceittech/voiceit2-nodejs#3]
HII,
I am  passing audioFilePath value is empty.I am getting error.

{ userId: 'usr_073a14cf83cc42c785854a1716292009',
  contentLanguage: 'en-US',
  audioFilePath: '' }
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: EISDIR: illegal operation on a directory, read

**Comment by hismaeel** [comment]
You are missing the closing quote mark in 
```
audioFilePath:"}
```

**Comment by armaanbindra** [comment]
We have now resolved this by adding a file check to all calls that throws a File Not Found error when you pass a non-existent file path like above, instead of a general stream error.
